version: '3.9'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    environment:
      - DATABASE_URL="postgresql://course_role:mypassword@db:5432/myappdb"
    depends_on:
      - db

  db:
     image: postgres:latest
     environment:
       POSTGRES_USER: course_role
       POSTGRES_PASSWORD: mypassword
       POSTGRES_DB: myappdb
     ports:
       - "5432:5432"  

    

        







 
