name: Module 7 Workflow

on: [push]

jobs:
  web:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: course_role
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: myappdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U course_role  -d myappdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/new_db
      DATABASE_URL: postgresql://course_role:mypassword@localhost:5432/myappdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alembic

      - name: Run migrations
        run: alembic upgrade head

      - name: Run application
        run: |
          pytest tests/


  

  docker-build:
    runs-on: ubuntu-latest
    needs: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .


  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to Server
        run: |
          echo "Deploying application..."
          # Add your deployment commands here e.g, using Docker or cloud providers
          # docker run -d -p 80:80 myapp:latest   








