name: Module 7 Workflow

on: [push]

jobs:
  web:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run application
      run: |
        uvicorn main:app --host